sudo: required
services:
  - docker

before_install:
  - docker build -t danielshiloah/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true danielshiloah/docker-react npm run test 